export const petPool = {
  common: [
    { petId: "slime", name: "Slime", emoji: "🦠", hp: 55, atk: 4, def: 6 },
    { petId: "rat", name: "Rat", emoji: "🐀", hp: 35, atk: 8, def: 2 },
    { petId: "bat", name: "Bat", emoji: "🦇", hp: 40, atk: 7, def: 3 },
    { petId: "frog", name: "Frog", emoji: "🐸", hp: 50, atk: 5, def: 4 },
    { petId: "chicken", name: "Chicken", emoji: "🐔", hp: 48, atk: 6, def: 2 },
  ],

  uncommon: [
    { petId: "boar", name: "Boar", emoji: "🐗", hp: 95, atk: 7, def: 8 },
    { petId: "snake", name: "Snake", emoji: "🐍", hp: 70, atk: 12, def: 4 },
    { petId: "hawk", name: "Hawk", emoji: "🦃", hp: 65, atk: 13, def: 3 },
    { petId: "wolf", name: "Wolf", emoji: "🐺", hp: 80, atk: 10, def: 6 },
    { petId: "lynx", name: "Lynx", emoji: "🐈", hp: 85, atk: 9, def: 4 },
  ],

  rare: [
    { petId: "bear", name: "Bear", emoji: "🐻", hp: 150, atk: 11, def: 12 },
    { petId: "panther", name: "Panther", emoji: "🐆", hp: 95, atk: 18, def: 6 },
    { petId: "falcon", name: "Falcon", emoji: "🦅", hp: 90, atk: 19, def: 5 },
    { petId: "tiger", name: "Tiger", emoji: "🐯", hp: 120, atk: 15, def: 9 },
    { petId: "rhino", name: "Rhino", emoji: "🦏", hp: 140, atk: 13, def: 7 },
  ],

  epic: [
    { petId: "golem", name: "Golem", emoji: "🗿", hp: 230, atk: 16, def: 18 },
    {
      petId: "phoenix",
      name: "Phoenix",
      emoji: "🔥",
      hp: 150,
      atk: 26,
      def: 8,
    },
    {
      petId: "shadowcat",
      name: "Shadow Cat",
      emoji: "🌘",
      hp: 135,
      atk: 28,
      def: 7,
    },
    {
      petId: "griffin",
      name: "Griffin",
      emoji: "🦁",
      hp: 180,
      atk: 22,
      def: 12,
    },
    {
      petId: "leviathan",
      name: "Leviathan",
      emoji: "🌊",
      hp: 210,
      atk: 20,
      def: 9,
    },
  ],

  mythic: [
    {
      petId: "voidserpent",
      name: "Void Serpent",
      emoji: "🦂",
      hp: 250,
      atk: 34,
      def: 16,
      skill: "Void Bite (15% hút máu)",
    },
    {
      petId: "timefalcon",
      name: "Time Falcon",
      emoji: "🦈",
      hp: 270,
      atk: 36,
      def: 14,
      skill: "Time Dash (10% đánh thêm lượt)",
    },
    {
      petId: "astralwolf",
      name: "Astral Wolf",
      emoji: "🐅",
      hp: 290,
      atk: 33,
      def: 18,
      skill: "Astral Howl (20% né)",
    },
    {
      petId: "abysslion",
      name: "Abyss Lion",
      emoji: "🦌",
      hp: 220,
      atk: 31,
      def: 20,
      skill: "Abyss Roar (giảm 20% atk địch)",
    },
    {
      petId: "thunderdrake",
      name: "Thunder Drake",
      emoji: "🐊",
      hp: 280,
      atk: 37,
      def: 15,
      skill: "Thunder Claw (15% x2 dmg)",
    },
  ],

  legendary: [
    {
      petId: "firephoenix",
      name: "Fire Phoenix",
      emoji: "🐦",
      hp: 350,
      atk: 22,
      def: 25,
    },
    { petId: "dragon", name: "Dragon", emoji: "🐉", hp: 360, atk: 35, def: 15 },
    { petId: "demon", name: "Demon", emoji: "😈", hp: 330, atk: 38, def: 13 },
    {
      petId: "celestial",
      name: "Celestial",
      emoji: "✨",
      hp: 360,
      atk: 28,
      def: 20,
    },
    {
      petId: "ancientbeast",
      name: "Ancient Beast",
      emoji: "🦖",
      hp: 330,
      atk: 26,
      def: 17,
    },
  ],

  special: [
    {
      petId: "goddragon",
      name: "God Dragon",
      emoji: "☀️",
      hp: 400,
      atk: 44,
      def: 25,
      skill: "Divine Wrath (25% hút máu + 30% crit)",
    },
    {
      petId: "voiddeity",
      name: "Void Deity",
      emoji: "⚫",
      hp: 410,
      atk: 45,
      def: 26,
      skill: "Void Collapse (40% bỏ qua DEF)",
    },
    {
      petId: "shadowapex",
      name: "Shadow Apex",
      emoji: "🌓",
      hp: 390,
      atk: 43,
      def: 24,
      skill: "Shadow Blitz (50% dodge + tăng SPD)",
    },
    {
      petId: "celestialking",
      name: "Celestial King",
      emoji: "👑",
      hp: 420,
      atk: 42,
      def: 27,
      skill: "Royal Blessing (hồi 20% HP mỗi turn)",
    },
    {
      petId: "chronosmaster",
      name: "Chronos Master",
      emoji: "⏳",
      hp: 380,
      atk: 46,
      def: 23,
      skill: "Time Rupture (2 lượt hành động liên tiếp)",
    },
  ],
};
